// <auto-generated />
using System;
using AuditVitals.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditVitals.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditVitalsDbContext))]
    [Migration("20260817012909_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditVitals.Domain.Entities.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("CrawledPageCount")
                        .HasColumnType("integer")
                        .HasColumnName("crawled_page_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DiscoveredPageCount")
                        .HasColumnType("integer")
                        .HasColumnName("discovered_page_count");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<int?>("HealthScore")
                        .HasColumnType("integer")
                        .HasColumnName("health_score");

                    b.Property<bool>("IsSampledAudit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sampled_audit");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("RequestedPageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("requested_page_limit");

                    b.Property<string>("RequestedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("requested_url");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_audits");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_audits_project_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_audits_status");

                    b.ToTable("audits", (string)null);
                });

            modelBuilder.Entity("AuditVitals.Domain.Entities.AuditFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<Guid?>("CrawledPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawled_page_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Evidence")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("evidence");

                    b.Property<string>("RecommendedFix")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("recommended_fix");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_code");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("WhyItMatters")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("why_it_matters");

                    b.HasKey("Id")
                        .HasName("pk_audit_findings");

                    b.HasIndex("AuditId")
                        .HasDatabaseName("ix_audit_findings_audit_id");

                    b.HasIndex("CrawledPageId")
                        .HasDatabaseName("ix_audit_findings_crawled_page_id");

                    b.HasIndex("RuleCode")
                        .HasDatabaseName("ix_audit_findings_rule_code");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_audit_findings_severity");

                    b.ToTable("audit_findings", (string)null);
                });

            modelBuilder.Entity("AuditVitals.Domain.Entities.AuditJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at_utc");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("locked_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_audit_jobs");

                    b.HasIndex("AuditId")
                        .IsUnique()
                        .HasDatabaseName("ix_audit_jobs_audit_id");

                    b.HasIndex("Status", "AvailableAtUtc")
                        .HasDatabaseName("ix_audit_jobs_status_available_at_utc");

                    b.ToTable("audit_jobs", (string)null);
                });

            modelBuilder.Entity("AuditVitals.Domain.Entities.CrawledPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("canonical_url");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<int>("CrawlDepth")
                        .HasColumnType("integer")
                        .HasColumnName("crawl_depth");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("H1Count")
                        .HasColumnType("integer")
                        .HasColumnName("h1_count");

                    b.Property<bool>("IsIndexable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_indexable");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("meta_description");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_url");

                    b.Property<long>("ResponseTimeMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("response_time_milliseconds");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id")
                        .HasName("pk_crawled_pages");

                    b.HasIndex("AuditId")
                        .HasDatabaseName("ix_crawled_pages_audit_id");

                    b.HasIndex("AuditId", "NormalizedUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_crawled_pages_audit_id_normalized_url");

                    b.ToTable("crawled_pages", (string)null);
                });

            modelBuilder.Entity("AuditVitals.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("LastAuditAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_audit_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("normalized_host");

                    b.Property<string>("RootUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("root_url");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("NormalizedHost")
                        .HasDatabaseName("ix_projects_normalized_host");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_projects_user_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("AuditVitals.Domain.Entities.Audit", b =>
                {
                    b.HasOne("AuditVitals.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audits_projects_project_id");
                });

            modelBuilder.Entity("AuditVitals.Domain.Entities.AuditFinding", b =>
                {
                    b.HasOne("AuditVitals.Domain.Entities.Audit", null)
                        .WithMany()
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_findings_audits_audit_id");

                    b.HasOne("AuditVitals.Domain.Entities.CrawledPage", null)
                        .WithMany()
                        .HasForeignKey("CrawledPageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_findings_crawled_pages_crawled_page_id");
                });

            modelBuilder.Entity("AuditVitals.Domain.Entities.AuditJob", b =>
                {
                    b.HasOne("AuditVitals.Domain.Entities.Audit", null)
                        .WithMany()
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_jobs_audits_audit_id");
                });

            modelBuilder.Entity("AuditVitals.Domain.Entities.CrawledPage", b =>
                {
                    b.HasOne("AuditVitals.Domain.Entities.Audit", null)
                        .WithMany()
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crawled_pages_audits_audit_id");
                });
#pragma warning restore 612, 618
        }
    }
}
